services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rmd-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/supportticket
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=secret
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: rmd-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: realtime-monitoring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: