name: CI/CD Pipeline - Realtime Monitoring

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: setting Java 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Permission for Maven Wrapper
      run: chmod +x mvnw

    - name: run backend tests
      run: ./mvnw test

    - name: Build app
      run: ./mvnw clean package -DskipTests

  docker-build:
    needs: build-and-test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repozitory
      uses: actions/checkout@v3

    - name: Build Backend Docker Image
      run: |
        docker build -t my-repo/realtime-monitoring-backend:latest ./backend