package com.realtime_monitoring_dashboard.backend.controller;

import com.realtime_monitoring_dashboard.backend.dto.AlertDTO;
import com.realtime_monitoring_dashboard.backend.service.AlertService;
import lombok.RequiredArgsConstructor;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.constraints.Positive;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping("/api/alerts")
@RequiredArgsConstructor
@CrossOrigin(origins = "*")
@Validated
@Tag(name = "Alerts", description = "Alerts generated by device status")
public class AlertController {

    private final AlertService alertService;

    @Operation(summary = "List of active alerts")
    @ApiResponse(responseCode = "200", description = "List successfully returned")
    @GetMapping
    public ResponseEntity<List<AlertDTO>> getActiveAlerts() {
        return ResponseEntity.ok(alertService.getActiveAlerts());
    }

    @Operation(summary = "Acknowledged alerts")
    @ApiResponse(responseCode = "200", description = "Alert acknowledged")
    @ApiResponse(responseCode = "404", description = "Alert with this ID does not exist")
    @PatchMapping("/{id}/acknowledge")
    public ResponseEntity<AlertDTO> acknowledgeAlert(@Parameter(description = "Device ID")@PathVariable @Positive Long id) {
        return ResponseEntity.ok(alertService.acknowledgeAlert(id));
    }

    @Operation(summary = "Resolved alerts")
    @ApiResponse(responseCode = "200", description = "Alert resolved")
    @ApiResponse(responseCode = "404", description = "Alert with this ID does not exist")
    @PatchMapping("/{id}/resolve")
    public ResponseEntity<AlertDTO> resolveAlert(@Parameter(description = "Device ID")@PathVariable @Positive Long id) {
        return ResponseEntity.ok(alertService.resolveAlert(id));
    }
}